repository: SWU-ACM-Lab/Navigation
repository_url: https://github.com/SWU-ACM-Lab/Navigation

timezone: Asia/Shanghai
lang: zh_CN

title: SWU-ACM Lab Navigator
alias_en: SWU-ACM Lab Navigator
alias_cn: 西南大学ACM实验室导航
description: A Navigation Website for SWU-ACM Lab
keywords: SWU-ACM Lab, Navigation
url: https://navi.swu-acm.cn/
established_at: "2016-10-01T00:00+08:00"

author: iROCKBUNNY
author_url: https://irockbunny.com
organization: TEELAB
organization_url: https://teelab.net
contact: contact[at]irockbunny[dot]com

image: /images/logo.png
logo: /images/logo.png
logo_dark: /images/logo-dark.svg
logo_white: /images/logo-white.svg

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - .gitignore
  - .travis.yml
  - LICENSE
  - README.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - script
  - vendor
